[[DeviceList]]
  Name = 'Mikrotik-Device'
  ProfileName = 'Mikrotik-Profile'
  Description = 'Mikrotik router'
  Labels = [ 'Mikrotik router' ]
  [DeviceList.Protocols]
  [DeviceList.Protocols.other]
    Address = 'simple01'
    Port = '300'
  [[DeviceList.AutoEvents]]
    Interval = '10m'
    OnChange = false
    SourceName = 'DataRate'
  [[DeviceList.AutoEvents]]
    Interval = '10m'
    OnChange = false
    SourceName = 'SignalQuality'    
 